// Copyright 2021 The Cockroach Authors.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.txt.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0, included in the file
// licenses/APL.txt.
package main

import __antithesis_instrumentation__ "antithesis.com/instrumentation/wrappers"

import (
	"io/ioutil"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"honnef.co/go/tools/analysis/lint"
	"honnef.co/go/tools/simple"
	"honnef.co/go/tools/staticcheck"
	"honnef.co/go/tools/stylecheck"
	"honnef.co/go/tools/unused"
)

const (
	readmeContent = `All of the code in this directory is generated by generate-staticcheck for use in Bazel.
`
	buildBazelContent    = `exports_files(["def.bzl"])`
	analysisFileTemplate = `// Code generated by generate-staticcheck; DO NOT EDIT.

//go:build bazel
// +build bazel

package {{ .Package }}

import (
	util "github.com/cockroachdb/cockroach/pkg/testutils/lint/passes/staticcheck"
	"golang.org/x/tools/go/analysis"
	"honnef.co/go/tools/{{ .CheckType }}"
)

var Analyzer *analysis.Analyzer

func init() {
{{ if eq .CheckType "unused" }}	Analyzer = {{ .CheckType }}.Analyzer.Analyzer{{ else }}	for _, analyzer := range {{ .CheckType }}.Analyzers {
		if analyzer.Analyzer.Name == "{{ .Check }}" {
			Analyzer = analyzer.Analyzer
			break
		}
	}{{ end }}
	util.MungeAnalyzer(Analyzer)
}
`
	defBzlFileTemplate = `# Code generated by generate-staticcheck; DO NOT EDIT.

STATICCHECK_CHECKS = [
{{range $i,$a := .AllAnalyzers}}    "{{.}}",
{{end}}]
`
)

func main() {
	__antithesis_instrumentation__.Notify(40518)
	fileTpl := template.Must(template.New("source").Parse(analysisFileTemplate))
	rootDir := "build/bazelutil/staticcheckanalyzers"
	err := os.RemoveAll(rootDir)
	if err != nil {
		__antithesis_instrumentation__.Notify(40525)
		panic(err)
	} else {
		__antithesis_instrumentation__.Notify(40526)
	}
	__antithesis_instrumentation__.Notify(40519)
	err = os.MkdirAll(rootDir, 0755)
	if err != nil {
		__antithesis_instrumentation__.Notify(40527)
		panic(err)
	} else {
		__antithesis_instrumentation__.Notify(40528)
	}
	__antithesis_instrumentation__.Notify(40520)
	err = ioutil.WriteFile(filepath.Join(rootDir, "README.md"), []byte(readmeContent), 0644)
	if err != nil {
		__antithesis_instrumentation__.Notify(40529)
		panic(err)
	} else {
		__antithesis_instrumentation__.Notify(40530)
	}
	__antithesis_instrumentation__.Notify(40521)
	err = ioutil.WriteFile(filepath.Join(rootDir, "BUILD.bazel"), []byte(buildBazelContent), 0644)
	if err != nil {
		__antithesis_instrumentation__.Notify(40531)
		panic(err)
	} else {
		__antithesis_instrumentation__.Notify(40532)
	}
	__antithesis_instrumentation__.Notify(40522)

	var allAnalyzers []string
	for _, check := range []struct {
		Analyzers []*lint.Analyzer
		CheckType string
	}{

		{Analyzers: staticcheck.Analyzers, CheckType: "staticcheck"},
		{Analyzers: stylecheck.Analyzers, CheckType: "stylecheck"},
		{Analyzers: simple.Analyzers, CheckType: "simple"},
		{Analyzers: []*lint.Analyzer{unused.Analyzer}, CheckType: "unused"},
	} {
		__antithesis_instrumentation__.Notify(40533)
		for _, v := range check.Analyzers {
			__antithesis_instrumentation__.Notify(40534)
			analyzer := v.Analyzer
			pkgname := strings.ToLower(analyzer.Name)
			dirname := filepath.Join(rootDir, pkgname)
			err := os.MkdirAll(dirname, 0755)
			if err != nil {
				__antithesis_instrumentation__.Notify(40539)
				panic(err)
			} else {
				__antithesis_instrumentation__.Notify(40540)
			}
			__antithesis_instrumentation__.Notify(40535)
			outFile, err := os.Create(filepath.Join(dirname, "analyzer.go"))
			if err != nil {
				__antithesis_instrumentation__.Notify(40541)
				panic(err)
			} else {
				__antithesis_instrumentation__.Notify(40542)
			}
			__antithesis_instrumentation__.Notify(40536)
			err = fileTpl.Execute(outFile, struct {
				Package   string
				Check     string
				CheckType string
			}{Package: pkgname, Check: analyzer.Name, CheckType: check.CheckType})
			if err != nil {
				__antithesis_instrumentation__.Notify(40543)
				panic(err)
			} else {
				__antithesis_instrumentation__.Notify(40544)
			}
			__antithesis_instrumentation__.Notify(40537)
			err = outFile.Close()
			if err != nil {
				__antithesis_instrumentation__.Notify(40545)
				panic(err)
			} else {
				__antithesis_instrumentation__.Notify(40546)
			}
			__antithesis_instrumentation__.Notify(40538)
			allAnalyzers = append(allAnalyzers, "//"+dirname)
		}
	}
	__antithesis_instrumentation__.Notify(40523)
	sort.Strings(allAnalyzers)
	fileTpl = template.Must(template.New("defbzl").Parse(defBzlFileTemplate))
	defBzlFile, err := os.Create(filepath.Join(rootDir, "def.bzl"))
	if err != nil {
		__antithesis_instrumentation__.Notify(40547)
		panic(err)
	} else {
		__antithesis_instrumentation__.Notify(40548)
	}
	__antithesis_instrumentation__.Notify(40524)
	err = fileTpl.Execute(defBzlFile, struct{ AllAnalyzers []string }{AllAnalyzers: allAnalyzers})
	if err != nil {
		__antithesis_instrumentation__.Notify(40549)
		panic(err)
	} else {
		__antithesis_instrumentation__.Notify(40550)
	}
}
