name: Local Roachtests
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
  
jobs:
  local_roachtest:
    runs-on: [self-hosted, basic_big_runner_group]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          submodules: true
      - name: compute metadata
        run: echo GITHUB_ACTIONS_BRANCH=${{ github.event.pull_request.number || github.ref_name}} >> "$GITHUB_ENV"
      - run: ./build/github/get-engflow-keys.sh
      - name: run local roachtests
        run: ./build/github/local-roachtest.sh crosslinux
      - uses: actions/upload-artifact@v4
        with:
          name: local_roachtest_test_summary.tsv
          path: artifacts/test_summary.tsv
      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: local roachtest artifacts
          path: artifacts
      - name: clean up
        run: ./build/github/cleanup-engflow-keys.sh
        if: always()
        
local_roachtest_fips:
    runs-on: [self-hosted, basic_runner_group_fips]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          submodules: true
      - name: compute metadata
        run: echo GITHUB_ACTIONS_BRANCH=${{ github.event.pull_request.number || github.ref_name}} >> "$GITHUB_ENV"
      - run: ./build/github/get-engflow-keys.sh
      - name: run local roachtests
        run: ./build/github/local-roachtest.sh crosslinuxfips
      - uses: actions/upload-artifact@v4
        with:
          name: local_roachtest_fips_test_summary.tsv
          path: artifacts/test_summary.tsv
      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: local roachtest (FIPS) artifacts
          path: artifacts
      - name: clean up
        run: ./build/github/cleanup-engflow-keys.sh
        if: always()
